# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "halsay"
repo_name: "ASR-TTS-paper-daily"
show_authors: True
show_links: True
show_badge: False
max_results: 100

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/asr-arxiv-daily.json'
json_gitpage_path: './docs/asr-arxiv-daily-web.json'
json_wechat_path: './docs/asr-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "ASR":
        filters: ["ASR", "Speech Recognition"]
    "TTS":
        filters: ["TTS", "Text to speech", "Speech Synthesis"]
